### ISSUE TITLE
SOCKET_OPT_NAGGLE is deprecated

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/sal-iface-6lowpan#13]
This was a mis-spelling of Nagle. The new option is SOCKET_OPT_NAGLE.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2258

**Comment by artokin** [comment]
At the moment set_option() and get_option() are unimplemented in sal-iface-6lowpan and therefore socket options are not used.

**Comment by bremoran** [comment]
One of the tests in this module uses SOCKET_OPT_NAGGLE. It needs to be renamed to SOCKET_OPT_NAGLE or, if I delete SOCKET_OPT_NAGGLE, the tests will fail to compile.

https://github.com/ARMmbed/sal-iface-6lowpan/blob/56b9b6785c79c2c30dd9355bb06e3820f59cc6d3/test/system_test/cp_socket_abstract_test.cpp#L2126

**Comment by artokin** [comment]
oh, sorry. I didn't notice that. I'll fix that.

**Comment by artokin** [comment]
Published version `1.0.8` that contains fix for deprecated socket option.
