### ISSUE TITLE
Dramatic increase of ROM size of test-nanostack_tcp

### ISSUE THREAD

**Issue by cyliangtw** [ARMmbed/sal-iface-6lowpan#14]
Last time, I evaluated sal-iface-6lowpan old version 1.0.7, test-nanostack-tcp ROM size is as well as 228KB. In these 2 days, I evaluated sal-iface-6lowpan new version 2.0.0, the ROM size is dramatic increase as large as 379KB.

**Comparison as below:**
_v1.0.7	test-nanostack_tcp.bin	ROM=228KB	ZI+RW=38KB
v2.0.0	test-nanostack_tcp.bin	ROM=379KB	ZI+RW=48KB_

Except nan0stack upgrade, is there any other module caused this dramatic increase ?
How to shrink this ROM size to fulfill 256KB Flash ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2501

**Comment by SeppoTakalo** [comment]
Hi Cyliangtw,

This is a test code with no specified target ROM sizes so there is no guarantee that it will be easily shrinked to fit 256 kB of flash.

Reason for size increase is that we are going forward on developing the Thread support for our stack and due the security requirements, our modules now directly depend on mbed TLS.

Br. Seppo
